version: '3.9'

services:
  api:
    ports:
      # Exposes application port.
    - "8015:8015"
    build:
      target: dev
    volumes:
      # Adds current directory as volume.
    - .:/app/src/
    environment:
      # Enables autoreload.
      TEST_TASK_RELOAD: "True"

  rmq:
    ports:
    - "15673:15672"

  redis:
    ports:
    - "6376:6379"

  db:
    ports:
    - "5440:5432"
